#!/bin/bash

help() {
  echo "Enable a cron service"
  echo ""
  echo "Usage:"
  echo "  zcron enable [options] <service_name> <service_schedule>"
  echo ""
  echo "Notice:"
  echo "  Use _ instead of * for schedule pattern (bug)"
  echo ""
  echo "Example:"
  echo "    # Run my_cron_service_name every minutes"
  echo "    zcron enable my_cron_service_name _/1 _ _ _ _"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1
  local service_schedule=${@:2}

  if [ -z "$service_name" ]; then
    log::error "service name is required, use --help to get help"
    exit 1
  fi

  if [ -z "$service_schedule" ]; then
    log::error "service schedule is required, use --help to get help"
    exit 1
  fi

  # cron::enable $@
  # echo "fuck: $service_name $service_schedule"
  cron::enable $service_name "$service_schedule"
}

run() {
  core $@
}

run $@
