#!/bin/bash

help() {
  echo "List cron services"
  echo "  default only enabled service"
  echo ""
  echo "Usage:"
  echo "  zcron list [options]"
  echo ""
  echo "Options:"
  echo "  -a, --all  Get all cron service, include not enabled"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local is_list_all="false"
  if [ "$1" = "-a" ] || [ "$1" = "--all" ]; then
    is_list_all=true
  fi

  local services=$(cron_list $is_list_all)

  print() {
    local index=$1
    local service_name=$2

    log "    $index $(color::success "$service_name")"
  }

  local services_count=$(cron_count $is_list_all)

  if [ "$is_list_all" = "true" ]; then
    if [ $services_count -eq 0 ]; then
      log "    (no avaliable services)(all)"
      exit 0
    fi

    log "cron services(all): $services_count"
  else
    if [ $services_count -eq 0 ]; then
      log "    (no avaliable services)(enabled)"
      exit 0
    fi

    log "cron services(enabled): $services_count"
  fi

  log ""

  array::each print $services
}

run() {
  core $@
}

run $@
