#!/bin/bash

help() {
  echo "Remove a cron service"
  echo ""
  echo "Usage:"
  echo "  zcron remove [options] [app_name]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1

  if [ -z "$service_name" ]; then
    log_error "service name is required, use --help to get help"
    exit 1
  fi

  cron_remove $service_name
}

run() {
  core $@
}

run $@
