#!/bin/bash

help() {
  echo "Get a cron service logs"
  echo ""
  echo "Usage:"
  echo "  zcron logs [options] [app_name]"
  echo ""
  echo "Options:"
  echo "  -f, --follow  Follow logs"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1
  local service_schedule=${@:2}

  if [ -z "$service_name" ]; then
    log::error "service name is required, use --help to get help"
    exit 1
  fi

  cron::status "$service_name" "$service_schedule"
}

run() {
  core $@
}

run $@
