#!/bin/bash

cron::get_service_name() {
  local name=$1
  echo $name
}

cron::parse_service_name() {
  local service_name=$1
  if [ "$service_name" = "" ]; then
    log::error "[cron::parse_service_name] service_name is required"
    exit 1
  fi

  echo $service_name
}

cron::get_service_path() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service=$(cron::get_service_name $1)
  echo "$PLUGIN_CRON_SERVICE_DIR/${service}"
}

cron::get_service_enabled_path() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service=$(cron::get_service_name $1)
  echo "$PLUGIN_CRON_SERVICE_ENABLED_DIR/${service}"
}

cron::get_service_log_path() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service=$(cron::get_service_name $1)
  echo "$PLUGIN_CRON_SERVICE_LOG_DIR/${service}"
}

cron::is_service_exist() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "[cron::is_service_exist] name is required"
    exit 1
  fi

  local service_path=$(cron::get_service_path $name)
  if [ ! -f $service_path ]; then
    echo "false"
  else
    echo "true"
  fi
}

cron::is_service_enabled() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "[cron::is_service_exist] name is required"
    exit 1
  fi

  local service_enabled_path="$PLUGIN_CRON_SERVICE_ENABLED_DIR/$name"
  if [ ! -f $service_enabled_path ]; then
    echo "false"
  else
    echo "true"
  fi
}

cron::has_service() {
  local name=$1

  # fix empty crontab list
  sudo crontab -l >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    echo "false"

    # fix dead service
    if [ "$(cron::is_service_exist $name)" = "true" ]; then
      cron::remove $name
    fi
    return
  fi

  cron::is_service_exist $name
}

cron::logs() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service_name=$(cron::get_service_name $1)
  if [ "$(cron::is_service_exist $1)" = "false" ]; then
    log::error "cron service($1) not found"
    exit 1
  fi

  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
    -f | --follow)
      os::set_var is_cron_logs_follow true
      shift
      ;;
    *)
      if [ "$(string::match $key ^-)" = "true" ]; then
        log::error "[cron::logs] unknown parameter \"$key\""
        exit 1
      fi

      shift
      ;;
    esac
  done

  local service_log_path=$(cron::get_service_log_path $name)
  if [ "$is_cron_logs_follow" = "true" ]; then
    sudo tail -f $service_log_path
  else
    sudo cat $service_log_path
  fi
}

cron::status() {
  local name=$1
  local schedule=$2
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service=$(cron::get_service_name $1)
  if [ "$(cron::is_service_exist $1)" = "false" ]; then
    log::error "cron service($1) not found"
    exit 1
  fi

  if [ "$(cron::is_service_enabled $name)" = "true" ]; then
    # try to fix dead service, maybe remove crontab manually by someone
    if [ -n "$schedule" ]; then
      cron::enable $name $schedule >>/dev/null 2>&1
    fi

    echo "running"
  else
    echo "none"
  fi
}

cron::enable() {
  local name=$1
  local schedule_pattern=${@:2}

  # @TODO replace _ => *
  schedule_pattern=$(echo "$schedule_pattern" | sed -e "s%_%*%g")

  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  if [ "$schedule_pattern" = "" ]; then
    log::error "schedule_pattern is required, such as 00 09 * * 1-5"
    exit 1
  fi

  local service=$(cron::get_service_name $name)
  if [ "$(cron::is_service_exist $name)" = "false" ]; then
    log::error "cron service($name) not found"
    exit 1
  fi

  # disable before enable
  cron::disable $name

  local service_enabled_path=$(cron::get_service_enabled_path $name)
  if [ -f "$service_enabled_path" ]; then
    log::error "cron service($name) has been enabled before"
    return
  fi

  # @TODO why set +e
  set +e
  sudo crontab -l >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    sudo crontab -l | grep $service_enabled_path >>/dev/null 2>&1
    if [ "$?" = "0" ]; then
      log::error "cron service($name) has been enabled before (2)"
      return
    fi

    sudo crontab -l >$PLUGIN_CRON_SERVICE_CRONTAB_TMP 2>>/dev/null
    sudo chmod 664 $PLUGIN_CRON_SERVICE_CRONTAB_TMP
  fi
  set -e

  local service_path=$(cron::get_service_path $name)
  local service_log_path=$(cron::get_service_log_path $name)

  # link to enable
  sudo ln -s $service_path $service_enabled_path

  # add to crontab
  if [ ! -f "$PLUGIN_CRON_SERVICE_CRONTAB_TMP" ]; then
    touch $PLUGIN_CRON_SERVICE_CRONTAB_TMP
  else
    sudo chmod 664 $PLUGIN_CRON_SERVICE_CRONTAB_TMP
  fi

  echo "${schedule_pattern} $service_enabled_path >> $service_log_path 2>&1" >>$PLUGIN_CRON_SERVICE_CRONTAB_TMP
  sudo crontab $PLUGIN_CRON_SERVICE_CRONTAB_TMP
  sudo rm $PLUGIN_CRON_SERVICE_CRONTAB_TMP

  echo "[enabled][$USER] $(date)" >>$service_log_path

  log::success "[cron::enable] cron service($name) enabled"
}

cron::disable() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service_name=$(cron::get_service_name $name)
  local service_enabled_path=$(cron::get_service_enabled_path $name)
  local service_log_path=$(cron::get_service_log_path $name)
  if [ "$(cron::is_service_exist $name)" = "false" ]; then
    log::error "cron service($name) not found"
    exit 1
  fi

  if [ ! -f "$service_enabled_path" ]; then
    log::info "cron service($name) is not enabled"
    return
  fi

  sudo crontab -l >>/dev/null 2>&1
  if [ "$?" = "0" ]; then
    # remove crontab
    sudo crontab -l >$PLUGIN_CRON_SERVICE_CRONTAB_TMP 2>>/dev/null
    sudo chmod 664 $PLUGIN_CRON_SERVICE_CRONTAB_TMP

    fs::remove_line_has_str $PLUGIN_CRON_SERVICE_CRONTAB_TMP $service_enabled_path

    # remove empty line
    #   reference: https://stackoverflow.com/questions/10347653/awk-remove-blank-lines
    # awk NF $PLUGIN_CRON_SERVICE_CRONTAB_TMP >$PLUGIN_CRON_SERVICE_CRONTAB_TMP
    fs::remove_empty_line $PLUGIN_CRON_SERVICE_CRONTAB_TMP

    sudo crontab $PLUGIN_CRON_SERVICE_CRONTAB_TMP
    sudo rm $PLUGIN_CRON_SERVICE_CRONTAB_TMP
  fi

  sudo unlink $service_enabled_path >>/dev/null

  echo "[disabled][$USER] $(date)" >>$service_log_path
}

cron::create() {
  local name=$1
  local schedule=$2
  local command=$3

  # echo "xxx:name: $name"
  # echo "xxx:schedule: $schedule"
  # echo "xxx:command: $command"

  if [ "$name" = "" ]; then
    log::error "cron name is required"
    exit 1
  fi

  if [ "$schedule" = "" ]; then
    log::error "cron schedule is required"
    exit 1
  fi

  if [ "$command" = "" ]; then
    log::error "cron command is required"
    exit 1
  fi

  # create script dir
  if [ ! -d $PLUGIN_CRON_SERVICE_ENABLED_DIR ]; then
    sudo mkdir -p $PLUGIN_CRON_SERVICE_ENABLED_DIR
  fi

  if [ "$(cron::is_service_exist $name)" = "true" ]; then
    local service_path=$(cron::get_service_path $name)
    log::error "found cron service(${name}), please it manual: ${service_path}"
    exit 1
  fi

  local service_name=$(cron::get_service_name $name)
  local service_path=$(cron::get_service_path $name)
  sudo touch $service_path

  # create script
  sudo tee $service_path >>/dev/null <<EOF
#!/bin/bash
export PATH=/usr/local/lib/zmicro/bin:\$PATH

${command}
EOF
  sudo chmod +x $service_path

  # auto enable
  # echo "cron::enable $name $schedule"
  cron::enable $name $schedule

  log::success "cron service ${name} created"
}

cron::remove() {
  local name=$1

  if [ "$name" = "" ]; then
    log::error "cron service and command are required"
    exit 1
  fi

  local service_name=$(cron::get_service_name $name)
  local service_path=$(cron::get_service_path $name)
  if [ "$(cron::is_service_exist $name)" = "false" ]; then
    log::error "cron service(${name}) not found"
    exit 1
  fi

  # disable before move
  cron::disable $service_name

  sudo rm $service_path

  log::success "cron service ${name} removed"
}

cron::list() {
  local is_list_all=$1

  # echo "is_list_all: $is_list_all"

  local service_files=""
  if [ "$is_list_all" = "true" ]; then
    service_files=$(ls $PLUGIN_CRON_SERVICE_DIR)
  else
    service_files=$(ls $PLUGIN_CRON_SERVICE_ENABLED_DIR)
  fi

  parser() {
    local index=$1
    local file_name=$2
    local service_name=$(cron::parse_service_name $file_name)

    # ignore enabled dir
    if [ "$service_name" = "enabled" ]; then
      return
    fi

    echo $service_name
  }

  array::each parser $service_files
}

cron::count() {
  local services=$(cron::list $@)

  array::length $services
}

export -f cron::get_service_name
export -f cron::parse_service_name
export -f cron::get_service_path
export -f cron::get_service_enabled_path
export -f cron::get_service_log_path
export -f cron::is_service_exist
export -f cron::is_service_enabled
export -f cron::has_service

export -f cron::logs
export -f cron::status
export -f cron::enable
export -f cron::disable

export -f cron::create
export -f cron::remove

export -f cron::list
export -f cron::count
